### ISSUE TITLE
In receiveMessage change AttributeNames to ['All'] instead of ['SentTimestamp']

### ISSUE THREAD

**Issue by dingledorf** [trandangtri/sqs-queue-bundle#24]
I'd like to check the ApproximateReceiveCount attribute but its not available since you only specify SentTimestamp.

Perhaps if you don't want to change it to All, allow some configuration to be made?

**Comment by trandangtri** [comment]
I updated the ReceiveMessage. Thanks for your suggestion @dingledorf
