### ISSUE TITLE
Error Handling in AbstractWorker::process

### ISSUE THREAD

**Issue by dudamariand** [trandangtri/sqs-queue-bundle#29]
Hi,
I'm having difficulty finding a way to log the exception messages that may occur while processing the message:

        try {
            $result = $this->execute($message);
        } catch (\Exception $e) {
            return false;
        }

Maybe remove the try/catch and let the developer catch his own exceptions?

Thanks.

**Comment by trandangtri** [comment]
Hi @dudamariand,

Sure, you could do by yourself as well. The try/catch in `AbstractWorker::process` to make sure the worker could get the final result from application workers (like yours) and then delete (if success) or retry (if failure).

Furthermore, you could add `-vvv` for getting more information
```
bin/console tritran:sqs_queue:worker reminder -vvv
```
