### ISSUE TITLE
Apparently, there's no way to set the MessageGroupId for FIFO queues

### ISSUE THREAD

**Issue by lucasan** [trandangtri/sqs-queue-bundle#30]
For FIFO queues the MessageGroupId param is required, but I don't see any method to set it.

I'm getting this error because of that

> The request must contain the parameter MessageGroupId.

**Comment by infinitely-young** [comment]
Same story! Really, need it.

**Comment by st0at** [comment]
I need it too.

**Comment by trandangtri** [comment]
Dear guys,

Sorry for a late response. I'm quite busy for my projects in my company. 
I have just release a new update for this issue, name `2.1.0` to support sending message to a FIFO queue. 

Now you could specify MessageGroupID (even MessageDeduplicationID) via construction or getter method of `Message` instance.

Please let me know if you still have any issue else in working with FIFO queue.

Thanks
