### ISSUE TITLE
Cannot run phpunit

### ISSUE THREAD

**Issue by quanfoo** [trandangtri/sqs-queue-bundle#33]
PHP version: 7.1.15
Debug logs:
`PHP Fatal error:  Cannot redeclare static Symfony\Bundle\FrameworkBundle\Test\KernelTestCase::$container as non static TriTran\SqsQueueBundle\Tests\app\KernelTestCase::$container in /app-vendor/tritran/sqs-queue-bundle/Tests/app/KernelTestCase.php on line 16
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/phpunit:0
PHP   2. PHPUnit\TextUI\Command::main() /usr/local/bin/phpunit:574
PHP   3. PHPUnit\TextUI\Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:153
PHP   4. PHPUnit\TextUI\Command->handleArguments() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:169
PHP   5. PHPUnit\Util\Configuration->getTestSuiteConfiguration() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:849
PHP   6. PHPUnit\Util\Configuration->getTestSuite() phar:///usr/local/bin/phpunit/phpunit/Util/Configuration.php:924
PHP   7. PHPUnit\Framework\TestSuite->addTestFiles() phar:///usr/local/bin/phpunit/phpunit/Util/Configuration.php:1022
PHP   8. PHPUnit\Framework\TestSuite->addTestFile() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:418
PHP   9. PHPUnit\Util\FileLoader::checkAndLoad() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:340
PHP  10. PHPUnit\Util\FileLoader::load() phar:///usr/local/bin/phpunit/phpunit/Util/FileLoader.php:49
PHP  11. include_once() phar:///usr/local/bin/phpunit/phpunit/Util/FileLoader.php:63
PHP  12. spl_autoload_call() /app-vendor/tritran/sqs-queue-bundle/Tests/Functional/Command/QueueAttCommandTest.php:13
PHP  13. Composer\Autoload\ClassLoader->loadClass() /app-vendor/tritran/sqs-queue-bundle/Tests/Functional/Command/QueueAttCommandTest.php:13
PHP  14. Composer\Autoload\includeFile() /app-vendor/tritran/sqs-queue-bundle/vendor/composer/ClassLoader.php:322
PHP  15. include() /app-vendor/tritran/sqs-queue-bundle/vendor/composer/ClassLoader.php:444`

**Comment by trandangtri** [comment]
Hi @quanfoo,
Would you please add more detail for this issue, such as Symfony version which you are using. Thanks

**Comment by trandangtri** [comment]
Fixed in #37. Thanks.
